# Generated by Django 2.2.8 on 2021-04-06 17:05

from django.db import migrations, models
import djongo.models.fields
import tfg_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('tfg_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GpsEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registry', djongo.models.fields.EmbeddedField(model_container=tfg_app.models.Registry, null=True)),
            ],
        ),
    ]
